### ISSUE TITLE
removes semicolon with one statement

### ISSUE THREAD

**Issue by inigohu** [lopezator/sqlfmt#2]
When you have only one statement, sqlfmt removes last semicolon.

for example:
```
INSERT
INTO
   table (id, name)
VALUES
   ('123', 'test');
```
returns
```
INSERT
INTO
   table (id, name)
VALUES
   ('123', 'test')
```

**Comment by lopezator** [comment]
Semicolon in SQL is a statement terminator, and not required when you are trying to execute a single SQL statement.

A SQL statement without semicolon is a valid SQL statement according to the SQL specification:

https://stackoverflow.com/questions/18941539/is-the-semicolon-necessary-in-sql
